apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patches:
  - target:
      kind: StatefulSet
      name: postgres
    patch: |
      - op: replace
        path: /spec/volumeClaimTemplates/0/spec/resources/requests/storage
        value: 200Gi
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/cpu
        value: "4"
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/memory
        value: 8Gi
