apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patches:
  - target:
      kind: ScaledObject
      name: pool-detection-scaler
    patch: |
      - op: replace
        path: /spec/maxReplicaCount
        value: 2
