apiVersion: v1
kind: Service
metadata:
  name: contact-enrichment-svc
  namespace: pool-prospect
spec:
  selector:
    app: contact-enrichment
  ports:
    - port: 8003
      targetPort: 8003
  type: ClusterIP
