apiVersion: v1
kind: Service
metadata:
  name: pool-detection-svc
  namespace: pool-prospect
spec:
  selector:
    app: pool-detection
  ports:
    - port: 8001
      targetPort: 8001
  type: ClusterIP
