apiVersion: v1
kind: Service
metadata:
  name: data-ingestion-svc
  namespace: pool-prospect
spec:
  selector:
    app: data-ingestion
  ports:
    - port: 8000
      targetPort: 8000
  type: ClusterIP
